### ISSUE TITLE
No Cats 🐈

### ISSUE THREAD

**Issue by trulyronak** [hexalellogram/CATS-OSS#3]
Where are the cats 🐱 

This is a pressing issue to me. I ask the community to join me in this demand

**Comment by steets250** [comment]
Thanks Ronak, very cool!

**Comment by hexalellogram** [comment]
🐶

**Comment by trulyronak** [comment]
THIS IS DOG OPRESSION

🐶

**Comment by steets250** [comment]
![bryce_emoji](https://user-images.githubusercontent.com/5706163/112744175-8d8f4880-8f52-11eb-89aa-3c2f7f616d44.png)
